### ISSUE TITLE
Offer for Sponsorship

### ISSUE THREAD

**Issue by maxammann** [m0nac0/flutter-maplibre-gl#30]
Hello m0naco!

Sorry for opening an issue, but I was unable to find any contact information to reach out to you directly.
The @digitalfabrik, @integreat and @ehrenamtskarte projects would like to thank you for taking over this project.
We event would like to extend the "thank you" by supporting this project financially.

You can reach out to me at ammann@integreat-app.de!

**Comment by m0nac0** [comment]
Thank you! Continued via e-mail.
